export { gql as shared } from "@shared/data-access";
export * from "./_scalar";
export * from "./comment/comment.gql";
export * from "./story/story.gql";
export * from "./board/board.gql";
export * from "./actionLog/actionLog.gql";
export * from "./report/report.gql";
export * from "./summary/summary.gql";
export * from "./chatRoom/chatRoom.gql";
export * from "./serviceDesk/serviceDesk.gql";
export * from "./emoji/emoji.gql";
export * from "./groupCall/groupCall.gql";
export * from "./user/user.gql";
export * from "./chatBoard/chatBoard.gql";
