apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongo
  namespace: localjobs-develop
spec:
  members: 1
  type: ReplicaSet
  version: 5.0.13
  replicaSetHorizons:
    - horizon: testnet.localjobs.mongo-0.tingting.com:31490
    # - horizon: testnet.localjobs.mongo-1.tingting.com:31491
    # - horizon: testnet.localjobs.mongo-2.tingting.com.com:31492
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: tingtingplanet
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: tingtingplanet
      roles:
        - name: root
          db: admin
      scramCredentialsSecretName: tingtingplanet
    - name: localjobs-develop-mongo-user
      db: localjobs-develop
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: localjobs-develop-mongo-user
      roles:
        - name: readWrite
          db: localjobs-develop
      scramCredentialsSecretName: localjobs-develop-mongo-user
  prometheus:
    username: mongo-prometheus
    passwordSecretRef:
      name: mongo-prometheus
  # additionalMongodConfig:
  #   storage.wiredTiger.engineConfig.journalCompressor: zlib
  statefulSet:
    spec:
      template:
        spec:
          nodeSelector:
            node-role.kubernetes.io/database: "true"
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - mongo
                  topologyKey: "kubernetes.io/hostname"
          initContainers:
            - name: change-dir-permissions
              command: ["chown", "-R", "2000", "/data", "/var/log"]
              image: busybox
              volumeMounts:
                - name: data-volume
                  mountPath: /data
                - name: logs-volume
                  mountPath: /var/log
              securityContext:
                runAsNonRoot: false
                runAsUser: 0
                runAsGroup: 0
          containers:
            - name: mongod
              resources:
                limits:
                  cpu: "0.2"
                  memory: 250M
                requests:
                  cpu: "0.2"
                  memory: 200M
            - name: mongodb-agent
              resources:
                limits:
                  cpu: "0.2"
                  memory: 250M
                requests:
                  cpu: "0.2"
                  memory: 200M
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 2G
            selector:
              matchLabels:
                namespace: localjobs-develop
                database: mongo
                type: data
            storageClassName: default
        - metadata:
            name: logs-volume
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 0.5G
            selector:
              matchLabels:
                namespace: localjobs-develop
                database: mongo
                type: logs
            storageClassName: default
---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      labels:
        namespace: localjobs-develop
        database: mongo
        type: data
      name: localjobs-develop-mongo-data-volume-0
    spec:
      accessModes:
        - ReadWriteOnce
      capacity:
        storage: 2G
      hostPath:
        path: /root/kubernetes/localjobs-develop/mongo/data-0
        type: ""
      # nodeAffinity:
      #   required:
      #     nodeSelectorTerms:
      #     - matchExpressions:
      #       - key: kubernetes.io/arch
      #         operator: In
      #         values:
      #         - amd64
      persistentVolumeReclaimPolicy: Delete
      storageClassName: default
      volumeMode: Filesystem
  # - apiVersion: v1
  #   kind: PersistentVolume
  #   metadata:
  #     labels:
  #       namespace: localjobs-develop
  #       database: mongo
  #       type: data
  #     name: localjobs-develop-mongo-data-volume-1
  #   spec:
  #     accessModes:
  #     - ReadWriteOnce
  #     capacity:
  #       storage: 2G
  #     hostPath:
  #       path: /root/kubernetes/localjobs-develop/mongo/data-1
  #       type: ""
  #     persistentVolumeReclaimPolicy: Delete
  #     storageClassName: default
  #     volumeMode: Filesystem
  # - apiVersion: v1
  #   kind: PersistentVolume
  #   metadata:
  #     labels:
  #       namespace: localjobs-develop
  #       database: mongo
  #       type: data
  #     name: localjobs-develop-mongo-data-volume-2
  #   spec:
  #     accessModes:
  #     - ReadWriteOnce
  #     capacity:
  #       storage: 2G
  #     hostPath:
  #       path: /root/kubernetes/localjobs-develop/mongo/data-2
  #       type: ""
  #     persistentVolumeReclaimPolicy: Delete
  #     storageClassName: default
  #     volumeMode: Filesystem
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      labels:
        namespace: localjobs-develop
        database: mongo
        type: logs
      name: localjobs-develop-mongo-logs-volume-0
    spec:
      accessModes:
        - ReadWriteOnce
      capacity:
        storage: 0.5G
      hostPath:
        path: /root/kubernetes/localjobs-develop/mongo/logs-0
        type: ""
      persistentVolumeReclaimPolicy: Delete
      storageClassName: default
      volumeMode: Filesystem
# - apiVersion: v1
#   kind: PersistentVolume
#   metadata:
#     labels:
#       namespace: localjobs-develop
#       database: mongo
#       type: logs
#     name: localjobs-develop-mongo-logs-volume-1
#   spec:
#     accessModes:
#     - ReadWriteOnce
#     capacity:
#       storage: 0.5G
#     hostPath:
#       path: /root/kubernetes/localjobs-develop/mongo/logs-1
#       type: ""
#     persistentVolumeReclaimPolicy: Delete
#     storageClassName: default
#     volumeMode: Filesystem
# - apiVersion: v1
#   kind: PersistentVolume
#   metadata:
#     labels:
#       namespace: localjobs-develop
#       database: mongo
#       type: logs
#     name: localjobs-develop-mongo-logs-volume-2
#   spec:
#     accessModes:
#     - ReadWriteOnce
#     capacity:
#       storage: 0.5G
#     hostPath:
#       path: /root/kubernetes/localjobs-develop/mongo/logs-2
#       type: ""
#     persistentVolumeReclaimPolicy: Delete
#     storageClassName: default
#     volumeMode: Filesystem
---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: mongo-svc-0
      namespace: localjobs-develop
    spec:
      type: NodePort
      selector:
        app: mongo-svc
        statefulset.kubernetes.io/pod-name: mongo-0
      ports:
        - protocol: TCP
          nodePort: 31490
          port: 31490
          targetPort: 27017
  # - apiVersion: v1
  #   kind: Service
  #   metadata:
  #     name: mongo-svc-1
  #     namespace: localjobs-develop
  #   spec:
  #     type: NodePort
  #     selector:
  #       app: mongo-svc
  #       statefulset.kubernetes.io/pod-name: mongo-1
  #     ports:
  #       - protocol: TCP
  #         nodePort: 31491
  #         port: 31491
  #         targetPort: 27017
  # - apiVersion: v1
  #   kind: Service
  #   metadata:
  #     name: mongo-svc-2
  #     namespace: localjobs-develop
  #   spec:
  #     type: NodePort
  #     selector:
  #       app: mongo-svc
  #       statefulset.kubernetes.io/pod-name: mongo-2
  #     ports:
  #       - protocol: TCP
  #         nodePort: 31492
  #         port: 31492
  #         targetPort: 27017
