version: "3"
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/jenkins:/var/jenkins_home
    ports:
      - "8100:8080"
    restart: unless-stopped
    privileged: true
    user: root
    environment:
      TZ: "Asia/Seoul"
      # JENKINS_OPTS: "--prefix=/jenkins"
